name: Python Calculator CI/CD

on:
  push:
    branches:
      - 'release'        # 모든 브랜치 push 시 테스트
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Python 설정
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: 테스트 실행
        run: pytest -q

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && needs.test.result == 'success'   # 조건부 실행
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4


      - name: 배포 스텝(예시)
        run: |
          echo "main 브랜치이므로 배포를 진행합니다."
          echo "${{ secrets.JEFF_SECRET_1 }}"
          # 실제 배포 스크립트를 여기에 작성하십시오.
