name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run tests
      id: run_tests
      run: |
        set -e
        python -m unittest -v
    - name: Send result to Discord
      if: always()
      env:
        DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1432753496184062014/SGOgSpawv4iNBf1mepM565Crlr7Wwlt7tmumcJqm-Tzj9U9NOY8pQbdREqcrEJwbV0Dh
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          message="✅ Tests passed on ${GITHUB_REPOSITORY}@${GITHUB_SHA}"
        else
          message="❌ Tests failed on ${GITHUB_REPOSITORY}@${GITHUB_SHA}"
        fi
        curl -H 'Content-Type: application/json' -X POST -d "{\"content\": \"$message\"}" "$DISCORD_WEBHOOK_URL"